export interface Matchers {
  readonly not: Matchers;
  readonly resolves: AsyncMatchers;
  readonly rejects: AsyncMatchers;
  toBe(expected: unknown): void;
  toEqual(expected: unknown): void;
  toStrictEqual(expected: unknown): void;
  toBeTruthy(): void;
  toBeFalsy(): void;
  toBeNull(): void;
  toBeUndefined(): void;
  toBeDefined(): void;
  toBeNaN(): void;
  toBeGreaterThan(n: number): void;
  toBeGreaterThanOrEqual(n: number): void;
  toBeLessThan(n: number): void;
  toBeLessThanOrEqual(n: number): void;
  toBeCloseTo(expected: number, numDigits?: number): void;
  toMatch(pattern: string | RegExp): void;
  toContain(item: unknown): void;
  toContainEqual(item: unknown): void;
  toHaveLength(n: number): void;
  toHaveProperty(keyPath: string | Array<string | number>, value?: unknown): void;
  toMatchObject(subset: object): void;
  toThrow(expected?: unknown): void;
  toHaveBeenCalled(): void;
  toHaveBeenCalledTimes(n: number): void;
  toHaveBeenCalledWith(...args: unknown[]): void;
  toHaveBeenLastCalledWith(...args: unknown[]): void;
  toHaveBeenNthCalledWith(n: number, ...args: unknown[]): void;
  toHaveReturned(): void;
  toHaveReturnedTimes(n: number): void;
  toHaveReturnedWith(value: unknown): void;
  toHaveLastReturnedWith(value: unknown): void;
  toHaveNthReturnedWith(n: number, value: unknown): void;
  [key: string]: unknown;
}

export interface AsyncMatchers {
  readonly not: AsyncMatchers;
  readonly resolves: AsyncMatchers;
  readonly rejects: AsyncMatchers;
  toBe(expected: unknown): Promise<void>;
  toEqual(expected: unknown): Promise<void>;
  toStrictEqual(expected: unknown): Promise<void>;
  toBeTruthy(): Promise<void>;
  toBeFalsy(): Promise<void>;
  toBeNull(): Promise<void>;
  toBeUndefined(): Promise<void>;
  toBeDefined(): Promise<void>;
  toBeNaN(): Promise<void>;
  toBeGreaterThan(n: number): Promise<void>;
  toBeGreaterThanOrEqual(n: number): Promise<void>;
  toBeLessThan(n: number): Promise<void>;
  toBeLessThanOrEqual(n: number): Promise<void>;
  toBeCloseTo(expected: number, numDigits?: number): Promise<void>;
  toMatch(pattern: string | RegExp): Promise<void>;
  toContain(item: unknown): Promise<void>;
  toContainEqual(item: unknown): Promise<void>;
  toHaveLength(n: number): Promise<void>;
  toHaveProperty(keyPath: string | Array<string | number>, value?: unknown): Promise<void>;
  toMatchObject(subset: object): Promise<void>;
  toThrow(expected?: unknown): Promise<void>;
  toHaveBeenCalled(): Promise<void>;
  toHaveBeenCalledTimes(n: number): Promise<void>;
  toHaveBeenCalledWith(...args: unknown[]): Promise<void>;
  toHaveBeenLastCalledWith(...args: unknown[]): Promise<void>;
  toHaveBeenNthCalledWith(n: number, ...args: unknown[]): Promise<void>;
  toHaveReturned(): Promise<void>;
  toHaveReturnedTimes(n: number): Promise<void>;
  toHaveReturnedWith(value: unknown): Promise<void>;
  toHaveLastReturnedWith(value: unknown): Promise<void>;
  toHaveNthReturnedWith(n: number, value: unknown): Promise<void>;
  [key: string]: unknown;
}
